dist: xenial
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38
  allow_failures:
    - python: 3.8-dev
  fast_finish: true

install:
  - pip install tox codecov

script:
  - tox -v

after_success:
  - codecov --file .tox/py36/log/coverage.xml

deploy:
  provider: pypi
  user: ermakov
  password:
    secure: "fgMzuHLQg/FVYhfwUw/14B+7BLqt+EDSmOsXdhiVG/K0l5FPU+hHm3Pb7iCzK5Byz8p7lOloTluZ5gfBn2Nvm9uqNr+mtGXhTV0NPXzo5raLIC55jFrMd0WsG6H4wSQuZX2+1LLFrcNip4IKWd1Aqv3DWp1SIicmnX37VVQD9X5ci0ix2c6J7g6q8paIHs+aDMDoAcJgt0/oJ8Bw8wMWv2RGIVBZ4EMqXax9yBATMbtuMiQKpjrXg1TY8+NN7G+X/WvWBtYvFHK4OueoD+Sx6Z460lh9Gk3BT5dwJT1szbau1WdZ6Yzv1yrv4qSFS1U+FFOarAaZk3qIqzJpsMQpQYZEpnZZ38AsxH42vMtd7nRsBFQCAlU7B3QCXIR15qQvSHqi0sYPy7tTjzI6FoFXSJDXEHrHPSVbE9WZXyllLBmAOyK9Cv62AIuCHA5et701NJzy5ka0BdLGwDye/TfRyG+mQgwPmfTvzLlQ6cGJ50IXNambJ4qOvGjMEQfEyPl2b1AB6G1S02c/fqxUGD292NcfWsfVhNLWUeFIZTrt8JaazPYbpEV8HSwTZofL+BKNhrnz3LVlD+owvWJNd/bOO0P2aXiWSasMK3JBcMy0cZkXJnah/fcCH5icybyVLYF3ohtgGvqf7BNYdxBT0p25TwT04jKjHSRh+SR8yO6rXRU="
  on:
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_existing: true