dist: xenial
language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38
  allow_failures:
    - python: 3.8-dev
  fast_finish: true

install:
  - pip install tox codecov

script:
  - tox -v

after_success:
  - codecov --file .tox/3.6/log/coverage.xml
